version: 2.1

orbs: # use docker orb from circleci 
  docker: circleci/docker@2.0.1

# Define the jobs we want to run for this project
jobs:
  build-app-karsajobs: # detail job and step for running build and push image script using image node and image docker
    docker:
      - image: cimg/node:14.21
    steps:
      - checkout
      - setup_remote_docker: # setup remote docker to use docker cli
          version: 20.10.14
          docker_layer_caching: true
      - run: chmod +x build_push_image_karsajobs_ui.sh # change build push script permission
      - run: ./build_push_image_karsajobs_ui.sh # run build push script

# Orchestrate our job run sequence
workflows:
  lint_test_build:
    jobs:
      - docker/hadolint: # run lint with hadolint for dockerfile
          dockerfiles: './Dockerfile'
          ignore-rules: 'DL4005,DL3008'
      - build-app-karsajobs: # run build and push app job if test app is success
          requires:
            - docker/hadolint