version: 2.1

orbs:
  docker: circleci/docker@2.0.1

# Define the jobs we want to run for this project
jobs:
  test-app:
    docker:
      - image: cimg/go:1.15.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: cimg/go:1.15.15
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: chmod +x build_push_image_karsajobs.sh
      - run: ./build_push_image_karsajobs.sh

# Orchestrate our job run sequence
workflows:
  lint_test_build:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
          ignore-rules: 'DL4005,DL3008'
      - test-app:
          requires:
            - docker/hadolint
      - build-app-karsajobs:
          requires:
            - test-app
