version: 2.1

orbs:
  docker: circleci/docker@2.0.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/go:1.15.15
    steps:
      - checkout
      - run: echo "this is the build job"
  # test:
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout
  #     - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  lint_test_build:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
          ignore-rules: 'DL4005,DL3008'
      - test:
          requires:
            - docker/hadolint
